### ISSUE TITLE
RumiCarをArduinoライブラリ化する

### ISSUE THREAD

**Issue by takasehideki** [algyan/RumiCar#12]
Exerciseのディレクトリごとに`RumiCar.{h,ino}`がありますが，共通なものはライブラリ化してまとめるとよいと思います．ただしそのままではコンパイルが通るわけでは無さそうなので，少し修正は必要になります．
参考になりそうなページ：
https://qiita.com/exabugs/items/fe46ec45ff2ffd6c5777

よいこと：
- 開発者側：ライブラリを変更したい時に，全てのディレクトリのファイルを変更する必要が無くなる．その折りの作業漏れも避けられる．
- ユーザ側：
  - `RumiCar.{h,ino}`を見なくて良い（下手に編集されてしまうことも避けられる）
  - いったんZipをインストールできたら，いちいちファイルをコピーしたりしなくてもよい．

わるいこと：
- ハンズオン等の時に，「このZipファイルをArduinoライブラリとしてインストールしてください〜」が必要になる．
- ライブラリを更新した時には面倒かも．

**Comment by takasehideki** [comment]
Arduinoパッケージとして公式に登録できればユーザ操作も少なくて良さそうですが，どうやるといいかはArduino有識者の方にお任せします^^;
https://lang-ship.com/blog/work/arduino-ide-add-library-manager/

**Comment by takasehideki** [comment]
#21 にてExercise-3.2までライブラリ化を対応しました

**Comment by z10000** [comment]
> 
> 
> Exerciseのディレクトリごとに`RumiCar.{h,ino}`がありますが，共通なものはライブラリ化してまとめるとよいと思います．ただしそのままではコンパイルが通るわけでは無さそうなので，少し修正は必要になります．
> 参考になりそうなページ：
> https://qiita.com/exabugs/items/fe46ec45ff2ffd6c5777
> 
> よいこと：
> 
>     * 開発者側：ライブラリを変更したい時に，全てのディレクトリのファイルを変更する必要が無くなる．その折りの作業漏れも避けられる．
> 
>     * ユーザ側：
>       
>       * `RumiCar.{h,ino}`を見なくて良い（下手に編集されてしまうことも避けられる）
>       * いったんZipをインストールできたら，いちいちファイルをコピーしたりしなくてもよい．
> 
> 
> わるいこと：
> 
>     * ハンズオン等の時に，「このZipファイルをArduinoライブラリとしてインストールしてください〜」が必要になる．
> 
>     * ライブラリを更新した時には面倒かも．

RumiCar向けプログラムを開発する時や、ハンズオンでは予めVL53L0Xのライブラリのインストールが必要なので、それと同じように、事前準備でzip形式ライブラリをダウンロードしてインストールしていただけば良いので問題ないと思います。
