### ISSUE TITLE
LICENSEを設定する

### ISSUE THREAD

**Issue by takasehideki** [algyan/RumiCar#15]
OSSの流儀として，なにかしらライセンスを設定されると良いです．
利用側としても安心するおぢさんが多いです．

参考になりそうなページ
- https://qiita.com/shibukk/items/67ad0a5eda5a94e5c032
- https://qiita.com/medi-y-sato/items/c3d5c357ab020290dccc

**Comment by z10000** [comment]
MITライセンスにしてみました

**Comment by takasehideki** [comment]
よいとおもいます〜
