### ISSUE TITLE
関数名の変更の検討

### ISSUE THREAD

**Issue by takasehideki** [algyan/RumiCar#20]
`RC_setup` だと，RCサーボモータの設定だと思ってしまった^^;
RumiCarの略だと思われるので，`RumiCar_setup`,`RumiCar_steer`,`RumiCar_drive`に変更したほうがよいのでは？

**Comment by z10000** [comment]
良いと思います

**Comment by takasehideki** [comment]
これもかなり大きな変更になるのでリーダーの @Rumika685 さんの意向を確認しておきたいです．いかがでしょうか？
問題ないなら当方での対応は可能です．

**Comment by Rumika685** [comment]
RCの方が短いので、RCのままで良いと私は思います。

**Comment by takasehideki** [comment]
承知しました．ではこれは変更なしとしてCloseとさせていただきます．
（関数名って好みなので，リーダーの意向がイチバンです^^;
