### ISSUE TITLE
ソースコードのヘッダを適正にする

### ISSUE THREAD

**Issue by takasehideki** [algyan/RumiCar#22]
[./ArduinoAndESP32/Execise-1.1/Execise-1.1.ino](https://github.com/algyan/RumiCar/blob/master/ArduinoAndESP32/Exercise-1.1/Exercise-1.1.ino) などに，VL53L0Xのサンプルファイルのヘッダがそのまま残っている．

```
/* This example shows how to get single-shot range
  measurements from the VL53L0X. The sensor can optionally be
  configured with different ranging profiles, as described in
  the VL53L0X API user manual, to get better performance for
  a certain application. This code is based on the four
  "SingleRanging" examples in the VL53L0X API.

  The range readings are in units of mm. */

```

少なくとも削除したほうがよさそう．
加えて，RumiCarらしいヘッダファイルとできれば著作者・ライセンスを記載できるとよい．

**Comment by z10000** [comment]
取り急ぎ対象ファイルについては全部削除
かっこいい、ヘッダファイルなどは、後ほど。
ライセンスはRumiCarトップページにMITライセンス追加済

**Comment by takasehideki** [comment]
fixed at 2cd1385bbf99b01a2a8537a9a830dcbb4f48cba6 14428190f3376bc3cdcbdef13e2607d6727b3a63 98671e86e85790398f0b617fb6b8eb67721e9d8c aed92cf9bcd2255a64a35bb61da76ef0f40fb896 4965a8e5ea713ede6b0fe08b8c00b39df6f2c6ec 489e44ec2da432286df914a013ec3527e7adc1f0 9b1cb024365afc3c32e4f61c9b75d8df932dfcef e47c8e8a1c46db02ddde02a95d95bff6da13c2c9 2d5474b726df64920d83082ce913a97c58ddcbb1 570f495aef55f91c8d1229d4e6fb5281f0a4655f df798b44c1fe1143c2432211e9a57d8f9033feb2 c091d03e53a27e0592639aecb3d8cb1601400506 0c5ba806779a787ef7f0ac0616079822cf551dcb

**Comment by takasehideki** [comment]
ご検討・ご対応ありがとうございます．
ひとまずこれで良いと思いますので，Closeとさせてください．
